---
title: "GLMM"
author: "Han Songqiao"
date: "2022/3/2"
output:
  html_document:
    df_print: paged
---

Monte Carlo
```{r}
set.seed(123)
Conf=as.data.frame(matrix(nrow=100,ncol=2))
for (i in 1:100){
  n=500
  Sigma <- matrix(c(1,0.5,
                    0.5,1)
                  ,2,2)
  mn=mvrnorm(n, c(1,1), Sigma)
  lambda1=exp(mn[,1])
  lambda2=exp(mn[,2])
  data1=as.data.frame(matrix(nrow=n,ncol=2))
  colnames(data1)=c("gene1","gene2")
  data1$gene1=lambda1;data1$gene2=lambda2
  data1$Log_Lib_Size=log(sample(500:10000,n))
  M_Lib_Size=mean(data1$Log_Lib_Size)
  data1$L=data1$Log_Lib_Size-M_Lib_Size
  lambda1_new=lambda1*exp(data1$L)
  lambda2_new=lambda2*exp(data1$L)
  x1_new=rpois(n,lambda=lambda1_new)
  x2_new=rpois(n,lambda=lambda2_new)
  data1_new=data.frame(c(x1_new,x2_new))
  data1_new$gene=rep(1,2*n)
  data1_new$gene[(n+1):(2*n)]=2
  data1_new$id=rep(1:n,2)
  colnames(data1_new)[1]='count'
  data1_new$gene=as.factor(data1_new$gene)
  data1_new$id=as.factor(data1_new$id)
  data1_new$L=rep(data1$L,2)
  model1=glmer(count ~ gene+(0+gene|id)+offset(L),family=poisson,data=data1_new)
  var1 = diag(as.matrix(vcov(model1, full = TRUE, ranpar = "var")))[4]
  sd1=sqrt(var1)
  CI1=attr(VarCorr(model1)$id,"correlation")[2,1]+qnorm(0.025)*sd1
  CI2=attr(VarCorr(model1)$id,"correlation")[2,1]+qnorm(0.975)*sd1
  Conf[i,]=c(CI1,CI2)
}
```

```{r}
Conf[Conf$V1>0.5 | Conf$V2 <0.5,]
```

